# Generated by Django 3.2.2 on 2021-05-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='date',
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_do_pedido',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
