# Generated by Django 3.2.2 on 2021-05-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_pedido_confirmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
