# Generated by Django 3.2.2 on 2021-05-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0007_pedido_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='entregue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='saiu_para_entrega',
            field=models.BooleanField(default=False),
        ),
    ]
