# Generated by Django 3.2.2 on 2021-05-19 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0012_auto_20210519_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedido.endereco'),
        ),
    ]
