# Generated by Django 3.2.2 on 2021-05-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
